[package]
name = "stellarst0rm_github_io"
version = "0.3.0"

description = "My website!"
repository = "https://github.com/StellarSt0rm/stellarst0rm.github.io"
license = "MIT"

edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
toml = "0.8.19"
wasm-bindgen = "0.2.99"

[dependencies.web-sys]
version = "0.3.76"
features = [
    "Window",
    "Document",

    "HtmlElement",
    "HtmlCollection",
    "DomRect",
    "CssStyleDeclaration",

    "MouseEvent",
    "console",
]
